### ISSUE TITLE
"api_key" no definida en strings.xml

### ISSUE THREAD

**Issue by fdbozzo** [antoniolg/flow-workshop#1]
MainActivity.kt hace referencia a un string no definido:

TheMovieDbDataSource(getString(R.string.**api_key**))

Con lo que el ejemplo no compila y falla.

En el caso de que se indique una api_key válida en strings.xml, el error cambia a esto:

`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.antonioleiva.flowworkshop, PID: 6341
    java.lang.AbstractMethodError: abstract method "kotlinx.coroutines.DisposableHandle kotlinx.coroutines.Delay.invokeOnTimeout(long, java.lang.Runnable, kotlin.coroutines.CoroutineContext)"
        at kotlinx.coroutines.TimeoutKt.setupTimeout(Timeout.kt:145)
        at kotlinx.coroutines.TimeoutKt.withTimeout(Timeout.kt:44)
        at com.antonioleiva.flowworkshop.data.domain.MoviesRepository.checkRequireNewPage(MoviesRepository.kt:19)
        at com.antonioleiva.flowworkshop.data.domain.MoviesRepository$checkRequireNewPage$1.invokeSuspend(Unknown Source:12)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)`

**Comment by marxelosj** [comment]
Buenas, el api key lo debe crear en https://www.themoviedb.org/settings/api y agregarlo al strings.xml.

Para el error debería reemplazar ext.kotlin_version = "1.4.10" por ext.kotlin_version = "1.4.21" en el build.gradle de la app y ademas reemplazar id 'kotlin-android-extensions' por id 'kotlin-parcelize' en el build.gradle del modulo
e implementar implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.4.2'
